### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by archit0210** [pratikms/pratikms#1]
It will look more beautiful if we have sticky header while scrolling up

**Comment by pratikms** [comment]
I'm sorry @archit0210. Which sticky header are we talking about here?

**Comment by pratikms** [comment]
I see. Perhaps you were talking about changes which you already made in [your PR](https://github.com/saadpasta/developerFolio/pull/205) in the corresponding [parent repo](https://github.com/saadpasta/developerFolio). Based on your changes, I have also implemented [something similar](https://github.com/pratikms/portfolio/pull/272) in [my repo](https://github.com/pratikms/portfolio). To see what it looks like, you can check [https://pratikms.com/](https://pratikms.com/)

I'm closing this issue for now as I don't think this issue is related to this repo. Feel free to re-open it if I'm wrong.
